### ISSUE TITLE
Cannot detect tables 

### ISSUE THREAD

**Issue by adeeb2809** [tobiashey/PyTableOCR#1]
Hi,
I'm having some issues with the code
It cannot detect tables having small vertical lines and crashes the program

Here is an image of the table.
![Uploading img1.PNG…]()

Any help will be much appreciated
Thanks in advance.

**Comment by tobiashey** [comment]
First of all, your picture seems to be not loaded correctly.
Yes, i know its not perfect, resend the image and i can look into this.
What is your usecase @adeeb2809?

**Comment by adeeb2809** [comment]
Thanks for the reply

Here is another picture of the table
![img1](https://user-images.githubusercontent.com/63143429/111533452-0527d100-8724-11eb-821c-6922c2caff70.PNG)

When running the code tableOCR.py, it obtains an error and stops executing.

**Comment by tobiashey** [comment]
Had a bug in one of the filter functions, please try again. 
I atleast had no issues with the fixed version and your table. @adeeb2809

**Comment by adeeb2809** [comment]
It's working now.

Thanks :)
